### ISSUE TITLE
[QUERY] Does it make sense to create Jenkinsfile for this project?

### ISSUE THREAD

**Issue by VladyslavKurmaz** [WebbyLab/webbylab-starter-app-for-nodejs#3]

**Comment by koorchik** [comment]
Hi @VladyslavKurmaz ,
Currently, we use GitLab CI for CI/CD. We do not have Jenkins but we have intent to add .travis-ci.yml configuration as well as it is supported by Github.

As for the Jenkinsfile, unfortunately, we do not have possibility to support it. If you can maintain Jenkinsfile, you can add it. I guess it could be useful as a lot of companies use Jenkins.

**Comment by VladyslavKurmaz** [comment]
@koorchik to make this skeleton wide adopted, it's good to add support for major platforms/ecosystems. It shouldn't be something over-engineered, just simple templates which help developers start using this skeleton. I'm going to add support for Jenkins, Azure DevOps & SonarQube, if it's ok with your strategy.

**Comment by koorchik** [comment]
Yes, absolutely. Thank you! :)

**Comment by VladyslavKurmaz** [comment]
PR with first integration step is ready #7
