### ISSUE TITLE
After setup?

### ISSUE THREAD

**Issue by samrcruz** [WebbyLab/webbylab-starter-app-for-nodejs#5]
Hi after following the instructions on the readme file how can we test and try this out? do we have a list of endpoints exposed?

**Comment by ViraRodionova** [comment]
Hi @samrcruz! Currently our ApiDoc is in progress. You can look for public routes here: https://github.com/WebbyLab/webbylab-starter-app-for-nodejs/blob/master/lib/api/rest-api/main/router.mjs and admin routes here: https://github.com/WebbyLab/webbylab-starter-app-for-nodejs/blob/master/lib/api/rest-api/admin/router.mjs.

All routes, that check session, require an `Authorization` header with JWT value you receive after session creation.

Also, we can attach a Postman collection for RestAPI, if it is useful.

**Comment by samrcruz** [comment]
@ViraRodionova the Postman collection would be helpful!

**Comment by ViraRodionova** [comment]
@samrcruz  [Starter App.postman_collection.json.zip](https://github.com/WebbyLab/webbylab-starter-app-for-nodejs/files/4819100/Starter.App.postman_collection.json.zip)

**Comment by samrcruz** [comment]
thank you!
